name: got
channels:
  - conda-forge
  - defaults
dependencies:
  - ipykernel=5.3.4
  - ipython=7.19.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.1
  - jupyter=1.0.0
  - jupyter_client=6.1.7
  - jupyter_console=6.2.0
  - jupyter_core=4.7.0
  - jupyter_server=1.13.5
  - jupyterlab_pygments=0.1.2
  - jupyterlab_widgets=1.0.0
  - matplotlib-inline=0.1.6
  - notebook=6.5.6
  - numba=0.55.1
  - pip
  - python=3.7.9
  - scikit-learn-intelex=2021.2.2
  - six=1.15.0
  - tqdm
  - pip:
    - matplotlib==3.3.3
    - numpy==1.19.5
    - opencv-python==4.5.1.48
    - pillow==8.1.0
    - scikit-image==0.18.1
    - scikit-learn==0.24.0
    - scipy==1.6.0
    - xgboost==1.3.1
